import Head from "next/head";

export default function Home() {
  return (
    <div className=''>
      <div>
        <Head>
          <title>home</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='shortcut icon' href='favicon.ico' />
        </Head>
        <h1 className='text-5xl text-purple-500'>this is khalid umar</h1>
      </div>
    </div>
  );
}
